
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class UserManagement extends javax.swing.JFrame {

    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Users");
        setMinimumSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("UID :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 70, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("FULL NAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("LEVEL :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 260, 98, 18);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("EMAIL :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 320, 98, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("TELEPHONE NO :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 20, 100, 30);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 20, 110, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 80, 210, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Manager", "Accountant", "Employee" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 250, 120, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 310, 210, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(560, 20, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("USER NAME :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 70, 90, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("SEX :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 200, 29, 15);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(120, 200, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 210, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 270, 80, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 210, 80, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 370, 86, 32);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(560, 80, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("PASSWORD :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 140, 90, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("BASIC SALARY :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 120, 100, 70);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(120, 140, 210, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(480, 270, 80, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(560, 140, 150, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("CLEAR ALL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(540, 320, 100, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      //UserManagement um =new UserManagement();
       setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            PreparedStatement ps=null;
            ResultSet rs1=null;
            ResultSet rs2=null;
            
            String a= jTextField1.getText();
            String b= jTextField2.getText();
            String c= jTextField7.getText();
            String d= String.valueOf(jComboBox2.getSelectedItem());
            String e= String.valueOf(jComboBox1.getSelectedItem());
            String f= jTextField3.getText();
            String g= jTextField4.getText();
            String h= jTextField5.getText();
            String i=String.valueOf(jPasswordField1.getPassword());
           
            
//            if(a.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a user id !");
//            }
//            
//            if(b.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter Full Name !");
//            }
//            
//            if(c.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter Basic Salary !");
//            }
//            
//            if(d.equals("")){
//                JOptionPane.showMessageDialog(this, "Please select a gender !");
//            }
//            if(e.equals("")){
//                JOptionPane.showMessageDialog(this, "Please select a level!");
//            }
//             if(f.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a E-mail !");
//            }
//            if(g.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a Telephone Number !");
//            }
//            if(h.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a user name !");
//            }
//            if(i.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a password !");
//            } 
            
            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || f.equals("") || g.equals("") ||  h.equals("") || i.equals("") ){
                JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
//          jTextField1.setText("");
//         jTextField2.setText("");
//         jTextField3.setText("");
//         jTextField4.setText("");
//         jTextField5.setText("");
//         jPasswordField1.setText("");
//         jTextField7.setText("");
//         jComboBox1.setSelectedItem(null);
//         jComboBox2.setSelectedItem(null);
                   
                } 
            
            
//            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || f.equals("") || g.equals("") ||  h.equals("") || i.equals("") ){
//                try {
//                    ps.close();
//                } catch (SQLException ex) {
//                    Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
            

            String query_A="SELECT * FROM `login2` WHERE UserName=? ";
            ps=db.con().prepareStatement(query_A);
            ps.setString(1, h);
            rs1=ps.executeQuery();
            
            String query_B="SELECT * FROM `login2` WHERE password=? ";
            ps=db.con().prepareStatement(query_B);
            ps.setString(1, i);
            rs2=ps.executeQuery();
            
            if(rs1.next() || rs2.next()){
               JOptionPane.showMessageDialog(this, "User name and password has been used!");
          }
            else{
            String query= "INSERT INTO employee "
                    +"(UID,Name,User_Name,Password,Basic_Salary,Gender,Level,Email)"
                    +"VALUES (?,?,?,?,?,?,?,?)";
            ps=db.con().prepareStatement(query);
            
            
            ps.setString(1,a);
            ps.setString(2,b);
            ps.setString(3,h);
            ps.setString(4,i);
            ps.setString(5,c);
            ps.setString(6,d);
            ps.setString(7,e);
            ps.setString(8,f);
           // ps.setString(9,"a1");
           ps.execute();
             
           String query1="INSERT INTO etelephone "
                    +"(UID,TP)"
                    +"VALUES (?,?)";
           ps=db.con().prepareStatement(query1);
           ps.setString(2, g);
           ps.setString(1,a);
           ps.execute();
           
           String query2="INSERT INTO salary_details "
                    +"(UID,salary)"
                    +"VALUES (?,?)";
           ps=db.con().prepareStatement(query2);
           ps.setString(1, a);
           ps.setString(2,c);
           ps.execute();
           
           String query3="INSERT INTO login2 "
                    +"(UID,UserName,Password)"
                    +"VALUES (?,?,?)";
           
           ps=db.con().prepareStatement(query3);
           ps.setString(1,a);
           ps.setString(2,h);
           ps.setString(3,i);
           ps.execute();
          
           
            JOptionPane.showMessageDialog(this, "New User has been created");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField7.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jPasswordField1.setText("");
            jComboBox1.setSelectedItem(null);
            jComboBox2.setSelectedItem(null);
           // }
           
            
            
//       try{
//            PreparedStatement ps=null;
//            ResultSet rs= null;
//
//            String a= jTextField1.getText();   
//            if(a.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a user id !");
//            } 
//            try {
//            String b= jTextField2.getText();
//            if(b.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a user full name !");
//            } 
//            String c= String.valueOf(jComboBox2.getSelectedItem());
//            if(c.equals("")){
//                JOptionPane.showMessageDialog(this, "Please select the gender !");
//            } 
//            String d= String.valueOf(jComboBox1.getSelectedItem());
//            if(d.equals("")){
//                JOptionPane.showMessageDialog(this, "Please select the level !");
//            } 
//            String e= jTextField3.getText();
//            if(d.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter the e mail address !");
//            }
//            String f= jTextField4.getText();
//            if(f.equals("")){
//                //JOptionPane.showMessageDialog(this, "Please enter a telephome number !");
//
//            } 
//            String g= jTextField5.getText();
//             if(g.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a user name !");
//            } 
//            String h= jTextField6.getText();
//            if(h.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter a password!");
//            }
//            
//            String i= jTextField7.getText();
//            if(i.equals("")){
//                JOptionPane.showMessageDialog(this, "Please enter salary!");
//            }
//            
//            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || f.equals("") || g.equals("") ||  h.equals("") || i.equals("") ){
//                ps.close();
//            
//            }
//            String query = "INSERT INTO employee "
//                    + "UID,Name,UserName,Password,Basic_Salary,Gender,Level,Email"
//                    + "VALUES (?,?,?,?,?,?,?,?)";
//           
//            ps = db.con().prepareStatement(query);
//            ps.setString(1, a);
//            ps.setString(2, b);
//            ps.setString(3, g);
//            ps.setString(4, h);
//            ps.setString(5, i);
//            ps.setString(6, c);
//            ps.setString(7, d);
//            ps.setString(8, e);
//
//
//            
//            ps.execute();
//            JOptionPane.showMessageDialog(this, "New User has been creatd");
//
//        
//        }
//           catch (SQLException ex) {
//               Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
//           }        finally{
//                try {
//                    ps.close();
//                } catch (SQLException ex) {
//                    Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        
//        }
//
//    



//PreparedStatement ps=null;
//ResultSet rs= null;
//
//String query="INSERT INTO e "
//        +"(UID, Full_Name, Basic_Salary,Sex,level,Email,TP,User_Name,Password)"
//        +"VALUES(?,?,?,?,?,?,?,?,?)";
//
//            try {
//                ps = db.con().prepareStatement(query);
//            
//         String a=String.valueOf(jComboBox2.getSelectedItem());
//         String b=String.valueOf(jComboBox1.getSelectedItem());
//        
//        ps.setString(1,jTextField1.getText());
//        ps.setString(2,jTextField2.getText());
//        ps.setString(3,jTextField7.getText());
//        ps.setString(4,a);
//        ps.setString(5,b);
//        ps.setString(6,jTextField3.getText());
//        ps.setString(7,jTextField4.getText());
//        ps.setString(8,jTextField5.getText());
//        ps.setString(9,jTextField6.getText());
//         ps.executeUpdate();
//         JOptionPane.showMessageDialog(this, "New User has been creatd");
//        } catch (SQLException ex) {
//                Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
//            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            PreparedStatement ps=null;
            PreparedStatement ps2=null;
            PreparedStatement ps3=null;
            PreparedStatement ps4=null;
            
            ResultSet rs = null;
            ResultSet rs2 = null;
            ResultSet rs3 = null;
            ResultSet rs4 = null;
            
            String a=  jTextField1.getText();
            String b= jTextField5.getText();
            String query_a= "SELECT * FROM employee where UID =?";
            String query_b= "SELECT * FROM etelephone where UID =?";
            String query_c= "SELECT * FROM salary_details where UID =?";
            String query_d= "SELECT * FROM login2 where UID =?";
            
                   try { 
                      
            ps=db.con().prepareStatement(query_a);
            ps.setString(1, a);
            ps2=db.con().prepareStatement(query_b);
            ps2.setString(1, a);
            ps3=db.con().prepareStatement(query_c);
            ps3.setString(1, a);
            ps4=db.con().prepareStatement(query_d);
           ps4.setString(1, a);
            
          
            
            
            rs= ps.executeQuery();
            rs2=ps2.executeQuery();
            rs3=ps3.executeQuery();
            rs4=ps4.executeQuery();
           
           if(rs.next()&& rs2.next()&& rs3.next()&& rs4.next()){
           
            String query1= "DELETE  FROM employee where UID =?";
            String query2= "DELETE FROM etelephone where UID = ?";
            String query3= "DELETE  FROM salary_details where UID =?";
            String query4= "DELETE FROM login2 where UID = ?";
            
            ps=db.con().prepareStatement(query1);
            ps2=db.con().prepareStatement(query2);
            ps3=db.con().prepareStatement(query3);
            ps4=db.con().prepareStatement(query4);
            
            ps.setString(1, a);
            ps2.setString(1, a);
            ps3.setString(1, a);
            ps4.setString(1, a);
            
            
            ps.execute();
            ps2.execute();
            ps3.execute();
            ps4.execute();
             JOptionPane.showMessageDialog(this, "Deleted");
            
                 jTextField1.setText("");
                 jTextField2.setText("");
                 jTextField3.setText("");
                 jTextField4.setText("");
                 jTextField5.setText("");
                 jPasswordField1.setText("");
                 jTextField7.setText("");
                 jPasswordField1.setText("");
                 jComboBox1.setSelectedItem(null);
                 jComboBox2.setSelectedItem(null);
                      } 
           
          
                   else{
            JOptionPane.showMessageDialog(this, "No such a Employee!");
            jTextField1.setText("");
                 
                 
            
           
                 
                           }
                   }
           
         catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        finally{
                try {
                    ps.close();
                } catch (SQLException ex) {
                    Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              try {
            PreparedStatement psa=null;
            String a= jTextField1.getText();
            String b= jTextField2.getText();
            String c= jTextField7.getText();
            String d= String.valueOf(jComboBox2.getSelectedItem());
            String e= String.valueOf(jComboBox1.getSelectedItem());
            String f= jTextField3.getText();
            String g= jTextField4.getText();
            String h= jTextField5.getText();
            String i=String.valueOf(jPasswordField1.getPassword());

             if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || f.equals("") || g.equals("") ||  h.equals("") || i.equals("") ){
                
                   JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
//                   PreparedStatement psp=null;
//                   psp.close();
//                   jTextField1.setText("");
//         jTextField2.setText("");
//         jTextField3.setText("");
//         jTextField4.setText("");
//         jTextField5.setText("");
//         jPasswordField1.setText("");
//         jTextField7.setText("");
//         jComboBox1.setSelectedItem(null);
//         jComboBox2.setSelectedItem(null);
            
                   
                
             }
           {
            PreparedStatement ps=null;
            ResultSet rs = null;
            ResultSet rsa = null;
            ResultSet rsb = null;
            ResultSet rs1 = null;
            ResultSet rs2 = null;
            ResultSet rs3 = null;
            ResultSet rs4 = null;
            ResultSet rsc = null;            
            
            String query3= "UPDATE `employee` SET `Name`=?,`User_Name`=?,`Password`=?,`Basic_Salary`=?,`Gender`=?,`Level`=?,`Email`=? WHERE UID=?";
            String query4= "UPDATE `etelephone` SET `TP`=? WHERE UID = ?";
           
            
            PreparedStatement ps3=null;
            ResultSet rs3b=null;
            ps3=db.con().prepareStatement(query3);
         
            ps3.setString(1,b);
            ps3.setString(2,h);
            ps3.setString(3,i);
            ps3.setString(4,c);
            ps3.setString(5,d);
            ps3.setString(6,e);
            ps3.setString(7,f);
            ps3.setString(8,a);
            ps3.executeUpdate();
            
            
            PreparedStatement ps4=null;
            ResultSet rs7=null;
            ps4=db.con().prepareStatement(query4);
            ps4.setString(1, g);
            ps4.setString(2, a);
            ps4.executeUpdate();
            
             
            String query5= "UPDATE `salary_details` SET `salary`= ? WHERE UID = ?";
            
            PreparedStatement ps5=null;
            ResultSet rs5=null;
            ps5=db.con().prepareStatement(query5);
            ps5.setString(1, c);
            ps5.setString(2, a);
            ps5.executeUpdate();
            
            PreparedStatement ps6=null;
            String query6= "UPDATE `login2` SET `UserName`=?,`Password`=? WHERE UID=?";
            ps6=db.con().prepareStatement(query6);
            ps6.setString(1, h);
            ps6.setString(2, i);
            ps6.setString(3, a);
            ps6.executeUpdate();
            
               
        
       
        JOptionPane.showMessageDialog(this,"Updated");
        jTextField5.setVisible(true);
        jPasswordField1.setVisible(true);
        jLabel6.setVisible(true);
        jLabel8.setVisible(true);
         jTextField1.setText("");
         jTextField2.setText("");
         jTextField3.setText("");
         jTextField4.setText("");
         jTextField5.setText("");
         jPasswordField1.setText("");
         jTextField7.setText("");
         jComboBox1.setSelectedItem(null);
         jComboBox2.setSelectedItem(null);
            
            }    
        }catch (SQLException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                
        }                                 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ){
            System.out.println("dhfgdugyhdf");
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        ResultSet rs=null;
        try {
            String a= jTextField1.getText();
            String query ="SELECT  `Name`, `User_Name`, `Password`, `Basic_Salary`, `Gender`, `Level`, `Email` FROM `employee`  WHERE UID = ? ";
            PreparedStatement ps=null;
            ps=db.con().prepareStatement(query);
             ps.setString(1, a);
              rs=ps.executeQuery();
             
             String query2="SELECT `TP` FROM `etelephone`  WHERE UID = ? ";
             PreparedStatement ps2=null;
             ps2=db.con().prepareStatement(query2);
             ps2.setString(1, a);
             ResultSet rs2=null;
             rs2=ps2.executeQuery();
            
             if(rs2.next()){
                 jTextField4.setText(rs2.getString("TP"));
             }
           
        
            if(rs.next()){
                
            String Name = rs.getString("Name");
            String Basic_Salary = rs.getString("Basic_Salary");
            String Gender = rs.getString("Gender");
            String Level = rs.getString("Level");
            String Email = rs.getString("Email");
            String uname=rs.getString("User_Name");
            String pw =rs.getString("password");
           
            

           jTextField2.setText(Name);
           jTextField7.setText(Basic_Salary);
           jComboBox2.setSelectedItem(Gender);
           jComboBox1.setSelectedItem(Level);
           jTextField3.setText(Email);
           jTextField5.setText(uname);
           jPasswordField1.setText(pw);
            }

             else{
                JOptionPane.showMessageDialog(this, "User Not Found!");
                jTextField1.setText("");
                }
        
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VoucherHIstory.class.getName()).log(Level.SEVERE, null, ex);
        
    }
       
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                  jTextField1.setText("");
                 jTextField2.setText("");
                 jTextField3.setText("");
                 jTextField4.setText("");
                 jTextField5.setText("");
                 jPasswordField1.setText("");
                 jTextField7.setText("");
                 jPasswordField1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
